### ISSUE TITLE
Unable to switch repo when invalid repo is given

### ISSUE THREAD

**Issue by vigneshsankariyer1234567890** [CATcher-org/WATcher#101]
**Describe the bug**
When an invalid repo is given, the user is unable to switch to another repository. This could be related to #47 and needs to be handled.
 
**To Reproduce**

1. Run WATcher
2. Look up for an invalid repository (could be 'hello' or even 'hello/hello')
3. Following state occurs:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/68676914/226254734-5f13f962-eb28-4896-a19e-d67b4a02442d.png">

**Expected behavior**
I should be able to change the repo regardless of my input.

- OS: MacOS 12
- Browser Chrome
- Version node v 14

**Additional context**

**Comment by chunweii** [comment]
This has been fixed in #104.
