### ISSUE TITLE
Issues not showing for some repositories

### ISSUE THREAD

**Issue by chunweii** [CATcher-org/WATcher#107]
**Describe the bug**
For some repositories, the issues/PRs are not displayed.

**To Reproduce**
Try to access `chunweii/bugreporting` which has 14 issues, and 1 milestone. It shows:
![image](https://user-images.githubusercontent.com/47494777/227447242-2d2ccd36-e166-48c3-a7ff-75c94106f4e1.png)
The same thing happens for `kkangs0226/bugreporting` which has 9 issues and no milestones.

**Comment by vigneshsankariyer1234567890** [comment]
On investigation, I found that the reason for this was that none of the issues in this repo was assigned to you @chunweii. I have taken a look at #110 also and realised that the repo created by @Echomo-Xinyu , also does not have any issues assigned to him.

Currently, IssuesDataTable filters specifically by the assignee of the issue. If you take a look in `chunweii/bugreporting` or `kkangs0226/bugreporting`, none of the issues have any assignees. I have taken a screenshot of both repositories to show that both these repositories do not have any assignees (1st and 2nd screenshot). Currently, the issues for each assignee is generated through the IssuesViewerComponent, which goes through each assignee and and generates a CardViewComponent, as attached below in the 3rd screen shot. While this behaviour makes sense given that there are no assignees for those issues, I think we should add another CardViewComponent that houses all the issues which are unassigned. 

<img width="615" alt="image" src="https://user-images.githubusercontent.com/68676914/229472795-d67fe234-ecde-4a7c-91c9-8989f443c91b.png">
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/68676914/229472873-6657e2d1-39aa-4c06-a021-10434bd55daa.png">
<img width="475" alt="image" src="https://user-images.githubusercontent.com/68676914/229473885-4159cac4-b132-45ab-8dd5-b8ea96ab0b35.png">
