### ISSUE TITLE
Wrong octicon displayed for draft PR

### ISSUE THREAD

**Issue by Echomo-Xinyu** [CATcher-org/WATcher#109]
**Describe the bug**
similar to #75 

Currently, a draft PR is displayed as following:
<img width="206" alt="Screenshot 2023-03-24 at 5 28 15 PM" src="https://user-images.githubusercontent.com/25452497/227480731-2060fd68-6134-4860-976e-b7ee9ed5edf4.png">

However, the default look of a draft PR in GitHub should be as following:
<img width="394" alt="image" src="https://user-images.githubusercontent.com/25452497/227480707-fedb1d21-7910-4ed6-9196-d46b08a20744.png">

**To Reproduce**

1. Go to [WATcher](https://catcher-org.github.io/WATcher/)
2. Open repository "CATcher-org/WATcher-test"
3. See the wrong octicon displayed

**Expected behavior**
The octicon used by WATcher should align with GitHub.

**Desktop (please complete the following information):**

- OS: Mac Monterey
- Browser Google Chrome
- Version Version 111.0.5563.64 (Official Build) (arm64)

**Comment by wweqg** [comment]
Hi, can I work on this issue ?
