### ISSUE TITLE
Issue not shown in dashboard

### ISSUE THREAD

**Issue by Echomo-Xinyu** [CATcher-org/WATcher#110]
**Describe the bug**

Currently, there are two issues created by "Echomo-Xinyu" in the repository ["CATcher-org/WATcher-test"](https://github.com/CATcher-org/WATcher-test/issues?q=is%3Aissue)

<img width="1640" alt="image" src="https://user-images.githubusercontent.com/25452497/227712941-260db8e8-88d1-437e-83d5-1b43d23646fd.png">

However, the issues cannot be seen from the WATcher dashboard, despite the type selected is All.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/25452497/227713075-04f31c2f-80ee-4f5e-aa3d-2ebdfc3cba82.png">

**To Reproduce**

1. Go to WATcher and watch the "CATcher-org/WATcher-test"

**Expected behavior**
The issues should be shown clearly as well.

**Desktop (please complete the following information):**

- OS: Mac Monterey
- Browser: Chrome
- Version: Version 111.0.5563.64 (Official Build) (arm64)

**Comment by vigneshsankariyer1234567890** [comment]
Could this be related to #107?

**Comment by Echomo-Xinyu** [comment]
> Could this be related to #107?

Yes, I think they should be the same kind of bugs, at least appear to be the same.

**Comment by Eclipse-Dominator** [comment]
Issues fixed by #118
