### ISSUE TITLE
Small icon button to reset Label filter

### ISSUE THREAD

**Issue by gycgabriel** [CATcher-org/WATcher#112]
<img width="275" alt="Screenshot 2023-03-28 at 4 21 55 PM" src="https://user-images.githubusercontent.com/77230723/228174828-2c643741-da83-4a7c-a4e9-37ef0cea880d.png">

**Describe the solution you'd like**
Add a small icon to click to reset all hidden and selected labels. Easy reset.

**Additional context**
After filtering by many labels, or hiding labels, users may want a quick and easy way to reset the filter.
Icon can be placed on the right of the label search bar

**Comment by joyngjr** [comment]
Hey! Will it be alright if I work on this issue?
