### ISSUE TITLE
UI Improvements for when user name is too long 

### ISSUE THREAD

**Issue by kkangs0226** [CATcher-org/WATcher#127]
## Summary
<img width="288" alt="image" src="https://user-images.githubusercontent.com/66008784/230857604-ac397047-4636-4933-a73a-470dc2233fd2.png">

We can see that the user icon / number of issues & PRs overflow past the card if the user's name is too long. 

Let's wrap the username if it gets too long.

**Comment by seetohjinwei** [comment]
Hi! Is it okay for me to work on this issue?

**Comment by Eclipse-Dominator** [comment]
Yup, you can create PR to fix this! @seetohjinwei
