### ISSUE TITLE
Issues are not sorted by date updated correctly

### ISSUE THREAD

**Issue by chunweii** [CATcher-org/WATcher#137]
**Describe the bug**
In the issue dashboard, when I try to sort the issues/PRs by date updated, the sequence of cards remain the same as the previous order (sorted by ID), even though some of the issues that have a smaller ID have been more recently updated.

The value used to sort the issues or PRs is incorrect. Let's sort them by using the `updated_at` attribute in `Issue`.

**Comment by tarunsamanta2k20** [comment]
I'd like to work on this issue.

**Comment by chunweii** [comment]
@tarunsamanta2k20 Sure! You may make a pull request for this issue
