### ISSUE TITLE
Inconsistent error message for invalid repository

### ISSUE THREAD

**Issue by chia-yh** [CATcher-org/WATcher#152]
**Describe the bug**
Using an invalid repository name (e.g. `CATcher-org/invalid-repo`) when logging into WATcher gives a different error message from using an invalid repository name when switching repositories while logged in.

**To Reproduce**

1. Launch WATcher
2. Provide an invalid repository name
3. Login and see the first error message
4. Change repository, using the same invalid repository name, and see the second error message

**Expected behavior**
The error message for invalid repositories should be consistent.

**Screenshots**
When logging into WATcher with `CATcher-org/invalid-repo`:
![image](https://github.com/CATcher-org/WATcher/assets/105497890/89a93881-6e71-408d-85c8-0efd0d431e14)

When changing repositories to `CATcher-org/invalid-repo` while logged in:
![image](https://github.com/CATcher-org/WATcher/assets/105497890/ca85af9f-a53d-4632-8ea2-71c4f3168bc0)

Additionally, the former error message doesn't seem to directly inform users that the provided repository name is invalid.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome

**Additional context**
This issue seems to be consistently present on the initial launch of WATcher. Refreshing/logging out and entering the same invalid repository name before logging in again seems to show either error message inconsistently.

**Comment by joyngjr** [comment]
Hi, can I try working on this issue?
