### ISSUE TITLE
Login to Github before entering repository name

### ISSUE THREAD

**Issue by gycgabriel** [CATcher-org/WATcher#154]
**Context**
CATcher was designed with only one repository/ aka the phase repository in mind. For WATcher, you can change the repository, so it doesn't have to be fixed. A smoother UX would have the user login first then choose the repository they want to see 

**Describe the solution you'd like**
Ideally, Login to Github before entering repository name

**Comment by chia-yh** [comment]
Could I try attempting this issue?

**Comment by gycgabriel** [comment]
Yes do go ahead!

**Comment by gycgabriel** [comment]
I think this will be a step in the right direction for WATcher. 

Currently, the user can enter repository in two ways, and only the one on the Issue Viewer page validates that the repository is correct. This means that the user can enter an incorrect repository on the first page without error thrown to the user.

By moving the repository URL page after login, we can run Github requests to check the repository entered is valid the first time and request re-input from user if invalid.

Further iterations can remove the repository URL page and land directly on Issue Dashboard, with the Change repository popup to enter repository. This will help reuse code that we already have.

@CATcher-org/2223s2 @damithc What are your thoughts for this change?

**Comment by damithc** [comment]
Yes, I'm fine with the suggested change.

**Comment by chia-yh** [comment]
> I think this will be a step in the right direction for WATcher.
> 
> Currently, the user can enter repository in two ways, and only the one on the Issue Viewer page validates that the repository is correct. This means that the user can enter an incorrect repository on the first page without error thrown to the user.
> 
> By moving the repository URL page after login, we can run Github requests to check the repository entered is valid the first time and request re-input from user if invalid.
> 
> Further iterations can remove the repository URL page and land directly on Issue Dashboard, with the Change repository popup to enter repository. This will help reuse code that we already have.
> 
> @CATcher-org/2223s2 @damithc What are your thoughts for this change?

I think the suggestion to remove the repository URL page and land directly on Issue Dashboard and having the Change repository dialog pop up is a good idea, could I perhaps try implementing it in a separate PR as a possible alternative to the current change for comparison?
