### ISSUE TITLE
Default blue for icon is harsh on the eyes

### ISSUE THREAD

**Issue by gycgabriel** [CATcher-org/WATcher#155]
**Is your feature request related to a problem? Please describe.**
default html blue
<img width="399" alt="image" src="https://github.com/CATcher-org/WATcher/assets/77230723/bc042760-cecf-4d9f-bebd-d1e2a7f93e6e">
vs
<img width="402" alt="image" src="https://github.com/CATcher-org/WATcher/assets/77230723/a169a67e-fad0-4dc3-a83b-36e577f78579">

**Describe the solution you'd like**
#1D76DB
or 
#0073b5
or any other blue variant

**Context**
@Eclipse-Dominator's Detail page  #131

**Comment by fkamau1** [comment]
Hi @gycgabriel I am new to contributing but would like to work on this.

**Comment by gycgabriel** [comment]
> Hi @gycgabriel I am new to contributing but would like to work on this.

Yes please go ahead

**Comment by gycgabriel** [comment]
> Hi @gycgabriel I am new to contributing but would like to work on this.

Yes please go ahead, but do note to PR to [CATcher-org:Profile-page](https://github.com/CATcher-org/WATcher/tree/Profile-page) instead of master branch.
