### ISSUE TITLE
Collapse non-contributing user columns

### ISSUE THREAD

**Issue by gycgabriel** [CATcher-org/WATcher#156]
**Is your feature request related to a problem? Please describe.**
For WATcher, with multiple contributors, collapse excess contributors with blank columns

**Comment by seetohjinwei** [comment]
Hi! Could I try working on this issue?

- Would we want to completely hide the assignees without issues / PRs?
- Should this be based on currently applied filters or pre-filtering?
- Would we perhaps still want to display these users in a compacted list to the far right (after the unassigned issues)?
  - Users without PRs / Issues
    - Name 1
    - Name 2
    - ...

**Comment by gycgabriel** [comment]
Sure please go ahead.

1. We want to keep that information, we don't want to remove that. 
2. I don't understand the question, we want to remove columns that are empty because they take up space. E.g. If you load this repo on WATcher, there are some empty columns because of old contributors 
3. That would be ideal, also to maintain the style, include profile pic similar to the headers perhaps.

**Comment by seetohjinwei** [comment]
Thanks for the clarification!

For point 2, I meant the following flow

- Change `Status` from `All` to `Open`
- Some issues / PRs would be hidden
- If a user now has no issues / PRs (but has issues that are `Closed`, which are hidden), would they be considered a "User without PRs & Issues"?

Would something like this work?

<img width="701" alt="image" src="https://github.com/CATcher-org/WATcher/assets/47915290/d6d1c007-5975-458b-86e4-2f73bbe4ca5f">

**Comment by gycgabriel** [comment]
Yes if it doesn't cause too much changes to existing code, but it's also fine if its not done for when filtered

Main concern is prefiltered empty column

**Comment by seetohjinwei** [comment]
Okay, got it, I'll see if it is a simple change! Thank you :D

**Comment by chunweii** [comment]
As mentioned in https://github.com/CATcher-org/WATcher/pull/166#issuecomment-1626899376,

this feature is not needed for small teams. Closing issue.
