### ISSUE TITLE
Issue cards on dashboard are not longer interactable

### ISSUE THREAD

**Issue by Eclipse-Dominator** [CATcher-org/WATcher#171]
**Describe the bug**
For each PR/issues listed in the dashboard, it is expected that clicking it will redirect the user to the related Github page. However, right now the hyperlink is no longer working.

**Expected** (when hovered over)
![image](https://github.com/CATcher-org/WATcher/assets/4567895/293ec0d2-58ae-4ba6-8940-95e8fd31d8ae)

**Current** (when hovered over)
![image](https://github.com/CATcher-org/WATcher/assets/4567895/e3f994b1-7856-4a5f-9593-823ebdb5fb16)

**Comment by chia-yh** [comment]
I think this might have to do with using z-index in the scroll shadows, I'll see if I can fix it so that the hover + click functionality is restored
