### ISSUE TITLE
Long label name are hard to see in filter-bar

### ISSUE THREAD

**Issue by Eclipse-Dominator** [CATcher-org/WATcher#172]
**Describe the bug**
When having a dark background, the label text will be white and when the label overflows in the filterbar, the text can blend with the white background which makes it difficult to distinguish the text. 

![image](https://github.com/CATcher-org/WATcher/assets/4567895/7e9dac19-daa7-49f4-8485-d69a644a53fa)

**Comment by joyngjr** [comment]
Hi, can I work on this issue?
