### ISSUE TITLE
Add support for Issue Closed as Not Planned

### ISSUE THREAD

**Issue by gycgabriel** [CATcher-org/WATcher#186]
<img width="127" alt="image" src="https://github.com/CATcher-org/WATcher/assets/77230723/c32f8649-ca33-46f5-8665-d8be34c88c54">

Issue #4 and #2 of WATcher were Closed as Not Planned but appears as Closed

**Expected Behaviour**
Display the grey symbol like github

**Comment by joyngjr** [comment]
Hi, can I try working on this issue?
