### ISSUE TITLE
Hide unassigned issues column for PRs

### ISSUE THREAD

**Issue by joyngjr** [CATcher-org/WATcher#192]
**Describe the bug**
The column for unassigned issues remain when filtered by PRs even though it is irrelevant to the filter selection.

**To Reproduce**

1. Filter by 'Pull Requests'
2. Unassigned issues column remain

**Expected behavior**
Unassigned issues column gets hidden when user selects to filter by PRs.

**Screenshots**
![image](https://github.com/CATcher-org/WATcher/assets/97519138/7a98f3be-7fe4-4733-80e9-4d0e694c0810)

**Comment by LJXSean** [comment]
@joyngjr Hi is this issue still relavent?

**Comment by chunweii** [comment]
Perhaps as an extension to this issue, we can hide user columns which do not have any assigned issue or PR. 

We can also have a checkbox that will hide/show empty columns (including unassigned column)
