### ISSUE TITLE
Support full repo URL as well

### ISSUE THREAD

**Issue by damithc** [CATcher-org/WATcher#202]
When starting WATcher, user needs to specify the repo in `org/repo` format.
We can still proceed even if the user types in the full URL e.g., `https://github.com/AY2223S2-CS2103T-W13-1/tp`, simply by ignoring the first part of the URL.

**Comment by LJXSean** [comment]
Hi, i'd like to attempt this issue!

**Comment by LJXSean** [comment]
@damithc Hi prof, would this be applied only to the startup repo form or when changing repos in the /issuesViewer page as well?

![image](https://github.com/CATcher-org/WATcher/assets/110801974/c12500df-9d24-4595-aed5-e9034279ba89)

**Comment by damithc** [comment]
@LJXSean I think we can apply it anywhere the user enters the org/repo. Hopefully most of the fix can be applied in one place rather than duplicate everything in two places.
