### ISSUE TITLE
When changing repos, give a way to keep current filters

### ISSUE THREAD

**Issue by damithc** [CATcher-org/WATcher#205]
In the following scenario, we can give a way (e.g., add another button to the dialog) to let the user change the repo but keep the current filter settings.
This can be useful for tutors who are checking multiple team repos for the same things.

![image](https://github.com/CATcher-org/WATcher/assets/1673303/50542db8-1f51-4ea2-a276-aa38f27bca4f)

Work on saving the following filters
- [x] title (via search bar)
- [x] sort
- [x] status
- [x] type
- [x] selected labels
- [x] hidden labels
- [ ] milestones

**Comment by nknguyenhc** [comment]
Currently, we have had feature to keep filters when switching repo.
