### ISSUE TITLE
Update Angular version to 11.2.14

### ISSUE THREAD

**Issue by Arif-Khalid** [CATcher-org/WATcher#237]
**Is your feature request related to a problem? Please describe.**
Angular version is 10.2.5, it is very outdated.

**Describe the solution you'd like**
Update of angular version and relevant dependencies including node version supporting angular 11.2.14.

**Comment by chunweii** [comment]
Let's keep upgrading Angular for both CATcher and WATcher! CATcher is currently using Angular 11 so we need to upgrade WATcher's Angular asap!
