### ISSUE TITLE
Release changelogs automation

### ISSUE THREAD

**Issue by Arif-Khalid** [CATcher-org/WATcher#273]
**Is your feature request related to a problem? Please describe.**
Whenever a release is made, changelogs have to be manually typed.
This makes the changelogs prone to developer errors.
Developers also have to spend time looking through potentially many merged PRs and updating changelogs 1 by 1.

**Describe the solution you'd like**
An automated workflow that uses the merged PRs to generate template changelogs.
Possible solutions:
- Use a ready-made github bot: [https://probot.github.io/apps/release-drafter/](https://probot.github.io/apps/release-drafter/)
- Making a custom bot: [https://github.com/probot/probot](https://github.com/probot/probot)

Refer to the issue in CATcher: [https://github.com/CATcher-org/CATcher/issues/639](https://github.com/CATcher-org/CATcher/issues/639)
This solution using the release-drafter bot is already implemented in CATcher, it would make sense to have it in WATcher as well.

**Describe alternatives you've considered**
Keeping the workflow as is now and commit to spending time writing changelogs on every release

**Comment by Arif-Khalid** [comment]
@CATcher-org/active-devs @CATcher-org/2324s2 @CATcher-org/2223s2 @damithc 
What are your thoughts?

**Comment by vigneshsankariyer1234567890** [comment]
I think it's a pretty good idea, but would be difficult to implement especially if we have to parse through commit messages. Worth a shot if there is an available bot!
