### ISSUE TITLE
Add current filters to URL

### ISSUE THREAD

**Issue by nknguyenhc** [CATcher-org/WATcher#277]
**Is your feature request related to a problem? Please describe.**
As a follow up from #251, we should include filters into URL, and allow the filters to be shareable through URL as well.

**Describe the solution you'd like**
Add a query param to indicate filters for milestones, sort ID, etc, and apply the corresponding param upon landing onto the same URL, similar to #255 .

**Describe alternatives you've considered**
NIL

**Additional context**
As a follow up of #251.

**Comment by Arif-Khalid** [comment]
I like this idea and I believe it won't be very difficult to implement after #205 is closed. I will work on this when that happens.
