### ISSUE TITLE
Split 'Without a milestone' option

### ISSUE THREAD

**Issue by damithc** [CATcher-org/WATcher#297]
Current:

![image](https://github.com/CATcher-org/WATcher/assets/1673303/089f7fb6-22f2-4567-ad03-f0104d39a599)

Suggestion: Split option as 
```
...
[ ] PRs without a milestone
[ ] Issues without a milestone
```

Reason: The first category is of high interest (likely these are PRs the team forgot to assign to a milestone) while the second category is of low interest.

**Comment by MadLamprey** [comment]
While it is reasonable to separate the option, I believe it can also be achieved by selecting either PRs or Issues under `Type` and then selecting`Without a milestone` to get the desired result.

**Comment by damithc** [comment]
> While it is reasonable to separate the option, I believe it can also be achieved by selecting either PRs or Issues under `Type` and then selecting`Without a milestone` to get the desired result.

It's not the same. I want to see both PRs assigned to selected milestones as well as those without milestones (because PRs without a milestone are likely meant for the current milestone anyway -- I don't want to overlook them) but only issues assigned to the selected milestone (because there can be many issues not assigned for any milestone yet -- I don't want them to clutter my view).
