### ISSUE TITLE
Encode current view into the URL

### ISSUE THREAD

**Issue by damithc** [CATcher-org/WATcher#299]
It is good if the current view setting is encoded into the URL so that the current view can be shared easily with others (in other words, the user can control the landing view using the URL).
This is similar to how RepoSense works. Alternatively, there can be a 'Share current view' button that copies the encoded URL into the clipboard.

**Comment by nknguyenhc** [comment]
Hi prof, I think there is a similar issue #277 ?

**Comment by damithc** [comment]
> Hi prof, I think there is a similar issue #277 ?

Yes, closing in favor of the earlier issue, and upped its priority as well.
