### ISSUE TITLE
Autofill repository URL with Browser Cache

### ISSUE THREAD

**Issue by gycgabriel** [CATcher-org/WATcher#30]
**Is your feature request related to a problem? Please describe.**
It'll be nice to have repository URL autofilled and suggestions when the user accesses WATcher again. 

**Describe the solution you'd like**
Show repository URL autofill suggestions.

**Comment by chunweii** [comment]
This could be done by storing the repository location in the `localStorage`, and auto-filling the field with the stored value if there is one. I think it can be a good issue that is not too difficult to work on.

**Comment by chia-yh** [comment]
Hello, is it alright if I try working on this issue?

**Comment by gycgabriel** [comment]
Yes please go ahead!
