### ISSUE TITLE
Support preset views

### ISSUE THREAD

**Issue by damithc** [CATcher-org/WATcher#300]
Currently, we have ways for the user to finetune each aspect  of the issues dashboard view.
![image](https://github.com/CATcher-org/WATcher/assets/1673303/8f4d5a1a-2cab-4849-9ff5-5ebdd10ae396)

Suggestion: provide an easy way for users to reach commonly used preset views without having to hand-tune multiple aspect.

For example, a view I think most users will want to see the following (this could even be the default view):

`currently active`: all issues and PRs except closed PRs, assigned to the currently active milestone, including PRs (but not issues) that do not have a milestone, sorted by status (i.e., open issues/PRs on top)

What are other such presets that could be useful?
* `milestone X` all issues and PRs assigned to milestone X, sorted by ID(?)
* `contribution of JohnDoe`, showing what the person contributed to each milestone. But this is entirely different view from the current dashboard layout i.e., one column per each milestone

**Comment by NereusWB922** [comment]
I think it is a very good idea to have some preset views. To improve the flexibility of the view, we can implement the 'groupby' feature, which allows users to configure how columns are organized.

Some useful preset view and brief implementation:
'Active Pull Request': group by 'Assignee', filter by milestone (open milestone & without milestone), status (open), type (pr)
'Active Issues': group by 'Assignee', filter by milestone (open milestone), status (open), type (issue)
'My Contribution': group by 'Milestone' and filter by assignee (assigned to current user).

**Comment by NereusWB922** [comment]
I am willing to implement the "groupby" feature if you all think it is useful. @CATcher-org/2324s2

**Comment by Arif-Khalid** [comment]
@NereusWB922 I think it is a good functionality but you should create a separate issue more specific than this and link it to this one

**Comment by NereusWB922** [comment]
Just created a separate issue for group by feature #306

**Comment by nknguyenhc** [comment]
Possible preset views:
* Currently active: open PR, open issues, open milestone with the earliest deadline
* Contribution: the current default view, select all milestones

Put the preset view in the place of the `(Issue Dashboard)`. Put the word 'Custom' if preset view is not being used.

**Comment by damithc** [comment]
> Possible preset views:
> 
> * Currently active: open PR, open issues, open milestone with the earliest deadline
> * Contribution: the current default view, select all milestones
> 
> Put the preset view in the place of the `(Issue Dashboard)`. Put the word 'Custom' if preset view is not being used.

My proposed `currently active` view:
* issues (open/closed) assigned to the currently active milestone
* PRs (open/merged, but not closed) assigned to the currently active milestone
* PRs (open/merged, but not closed) without a milestone
* sorted by status (i.e., open issues/PRs on top)

**Comment by nknguyenhc** [comment]
One add on to the `currently active` view: If there is no currently open milestone, will default to the latest (by deadline) closed milestone.
