### ISSUE TITLE
Timeout after certain duration of graphql query and show error message

### ISSUE THREAD

**Issue by gycgabriel** [CATcher-org/WATcher#32]
**Is your feature request related to a problem? Please describe.**
For repositories larger than 200 issues or pull requests, WATcher may hang or crash from loading.

**Describe the solution you'd like**
Timeout after certain duration of graphql query and show error message

See https://github.com/CATcher-org/WATcher/issues/22#issuecomment-1193159356

**Comment by seetohjinwei** [comment]
Hi! Are we still intending to do this enhancement? If so, can I try to work on it?

I think we could use a `setTimeout` or similar mechanism in `withPagination` of `github.service.ts` to stop the recursion.

**Comment by gycgabriel** [comment]
Since I posted this issue, I think there have been changes to fetch queries more efficiently so loading CATcher repository on WATcher doesn't hang and crash as it used too. Compare 0.1.0 release https://catcher-org.github.io/WATcher/ vs npm run

I still think this is a good to have in case there are even bigger repositories that we need to timeout.

Please go ahead

**Comment by seetohjinwei** [comment]
I see! Thanks, I'll work on this!
