### ISSUE TITLE
Switch repository feature as a dialog

### ISSUE THREAD

**Issue by gycgabriel** [CATcher-org/WATcher#33]
**Is your feature request related to a problem? Please describe.**
The switch repository feature is dissimilar to Search or Filter. It should not be displayed in a similar manner to those features. On the other hand, there is scarce space to display it as a card as in the landing page. 

**Describe the solution you'd like**
Display a 'Switch repository' button, that throws a dialog that comprises the existing textbox and submit button.

**Describe alternatives you've considered**
Should the 'Switch repository' button be in the header, or should it be placed in the Issue Dashboard feature?

See #29

**Comment by cheehongw** [comment]
Duplicated issue of #45 
Resolved in #62
