### ISSUE TITLE
Disable milestone filter if no milestones 

### ISSUE THREAD

**Issue by gycgabriel** [CATcher-org/WATcher#36]
**Describe the bug**
No indication that there are no milestones 
Should disable filter by milestones dropdown

**To Reproduce**
Load a repository without milestones on issue dashboard

**Comment by seetohjinwei** [comment]
Hi! May I work on this issue?

Would it be better if the filter is completely hidden, or if there's text there to suggest that there are no milestones?

**Comment by damithc** [comment]
> Would it be better if the filter is completely hidden, or if there's text there to suggest that there are no milestones?

I think the latter is better (more informative) if it can be done in a natural and clean way.

**Comment by seetohjinwei** [comment]
> > Would it be better if the filter is completely hidden, or if there's text there to suggest that there are no milestones?
> 
> I think the latter is better (more informative) if it can be done in a natural and clean way.

Hi Prof! Would something like be better?

- Disable the selection
- Change the display text to `No Milestones`

![image](https://github.com/CATcher-org/WATcher/assets/47915290/65611bbe-8556-411b-9e05-9f7f4c90de12)

**Comment by damithc** [comment]
> Hi Prof! Would something like be better?
> 
> * Disable the selection
> * Change the display text to `No Milestones`

@seetohjinwei Yes, I think so.
