### ISSUE TITLE
Issues with the 'Invalid repo name' error

### ISSUE THREAD

**Issue by damithc** [CATcher-org/WATcher#367]
v1.2.2

![image](https://github.com/CATcher-org/WATcher/assets/1673303/88719df3-f9b1-4e9b-aff9-81ba4f0593a5)

If I give the wrong repo name in the above dialog, it keeps going back to the same dialog without any error message.

After I correct the error, it loads the correct view but shows the error message (which should have appeared earlier) as well.
![image](https://github.com/CATcher-org/WATcher/assets/1673303/b023f2cc-583e-4d15-b7db-6ef1523225f9)

Minor: the error was in the org name, not the repo name (i.e., the error message is slightly incorrect). Also, perhaps we can also include the faulty org/repo in the error message itself?

**Comment by NereusWB922** [comment]
Hi Prof @damithc, we can't reproduce the first issue on our local (i.e. no error message pop up for invalid repo). Is this still an issue on your side?

**Comment by damithc** [comment]
Cannot reproduce it myself. Closing ...
