### ISSUE TITLE
The hover over mouse icon doesn't indicate that PR/issue name is clickable

### ISSUE THREAD

**Issue by damithc** [CATcher-org/WATcher#368]
v1.2.2

![image](https://github.com/CATcher-org/WATcher/assets/1673303/ed79b4c8-1298-4660-88cd-a8c599afb300)

Expected: The mouse icon should change to a hand when hovering over a clickable item such as the issue/PR title?

On a related note,  perhaps different things on a card should go to different pages e.g., milestone icon should go to the corresponding milestone page?

**Comment by JiaXinEu** [comment]
May I work on this issue?

**Comment by Arif-Khalid** [comment]
@JiaXinEu You are most welcome to make a PR with your proposed fix. Thanks for your help.

**Comment by JiaXinEu** [comment]
Hi, I have sent a PR with the proposed change #380
