### ISSUE TITLE
Incorrect error message

### ISSUE THREAD

**Issue by nknguyenhc** [CATcher-org/WATcher#376]
From #367 

![image](https://github.com/CATcher-org/WATcher/assets/87511888/3db4ffb9-a01a-4c79-94e4-dff204216950)

The above error message always appear whenever the repo is invalid. Sometimes it is due to org name, not repo name. The error message can be improved.

**Comment by kokerinks** [comment]
Hi can I work on this?

**Comment by nknguyenhc** [comment]
> Hi can I work on this?

@kokerinks Sure, let us know your approach.

**Comment by kokerinks** [comment]
Hi, have created a PR which specifies the changes proposed. If this is ok I will start on the necessary changes to the documentation as well
