### ISSUE TITLE
Responsiveness of filters

### ISSUE THREAD

**Issue by Arif-Khalid** [CATcher-org/WATcher#377]
**Is your feature request related to a problem? Please describe.**
When the screen width is reduced, the filter bars are cut off and not a responsive design

**Describe the solution you'd like**
A togglable hamburger when the width reaches a certain minimum that houses filters

**Describe alternatives you've considered**
Making the filters on top of one another is also possible but might create a really long page

**Additional context**
Before reducing screen width
![image](https://github.com/CATcher-org/WATcher/assets/88131400/9f984bf8-cf83-45d6-9660-113481223caa)

After reducing screen width
![image](https://github.com/CATcher-org/WATcher/assets/88131400/78476b6e-4082-44c1-a9a2-5af283e8fa6a)

**Comment by JiaXinEu** [comment]
Hi, may I try to work on this?

**Comment by Arif-Khalid** [comment]
That would be great please go ahead

**Comment by JiaXinEu** [comment]
Would it be fine if the proposed PR is different from the described solution
