### ISSUE TITLE
UI Improvements for when there are too many users 

### ISSUE THREAD

**Issue by kkangs0226** [CATcher-org/WATcher#52]
![image](https://user-images.githubusercontent.com/66008784/211967709-16a3a4bc-7a4a-4634-b52a-9f48bc29daa7.png)

The list of users extend beyond the header

**Comment by vigneshsankariyer1234567890** [comment]
Any suggestions on how it should look like? I was thinking we can have a horizontal scroll container.

**Comment by chunweii** [comment]
> Any suggestions on how it should look like? I was thinking we can have a horizontal scroll container to contain the Issue Tables.

That is a good solution.

Alternatively, we can also add some filter dropdown to select the github users to be displayed. This will of course be more complex.

**Comment by vigneshsankariyer1234567890** [comment]
> Alternatively, we can also add some filter dropdown to select the github users to be displayed. This will of course be more complex.

We could do it both ways actually. The filter dropdown would allow users to add and remove users to be displayed easily, so I think it's a good-to-have even if its more complex. On top of that, each user could also have a remove button like an X. Perhaps something like the screenshot below.

![image](https://user-images.githubusercontent.com/68676914/216804213-832815b5-d4d0-43cc-a6ed-17f285d1a1a4.jpg)

**Comment by damithc** [comment]
For the moment, let's give priority to optimizing for our primary target users i.e., CS2103/T students, which means the team size will be 4-6.
