### ISSUE TITLE
Support private repositories

### ISSUE THREAD

**Issue by gycgabriel** [CATcher-org/WATcher#6]
**Is your feature request related to a problem? Please describe.**
For WATcher to support NUS modules that use private repositories

**Describe the solution you'd like**
WATcher can work with private repositories

Change 'public_repo' permission parameter that is used in GithubService when fetching data.

**Comment by joyngjr** [comment]
Hi! Can I try working on this issue?

**Comment by gycgabriel** [comment]
Please go ahead @joyngjr
