### ISSUE TITLE
304 error when going to previous page

### ISSUE THREAD

**Issue by vigneshsankariyer1234567890** [CATcher-org/WATcher#65]
**Describe the bug**
After logging into a repository session, when I try to go back to the previous page, I don't end up going to the landing page but rather back to the issuesViewer page. Since we are redirected back to the issuesViewer page, the GitHub API is queried again and hence a 304 Server not modified error is returned. I think this is incorrect behaviour on 2 fronts: 

1. If the current repo name has not changed, why should the GitHub API be queried again?
2. Going back should not redirect the user back to the issuesViewer page, but the landing page (this is up for debate)

**To Reproduce**

1. Go to the landing page
2. Login as per usual, and key in a valid repository
3. Complete login process 
4. On IssuesViewer page, go back to previous page
5. See error

**Expected behavior**
1. If the name of the repository has not changed on the repo form, the GitHub API should not be queried.
2. If the user goes back to previous page, user should go back to the landing page. 

**Screenshots**

https://user-images.githubusercontent.com/68676914/216007690-e00ec29f-2c4f-4f2f-8f7d-3965c3bd51f6.mov

**Desktop (please complete the following information):**

- OS: MacOS Monterey
- Browser Chrome
- Version 105

**Additional context**

**Comment by cheehongw** [comment]
I think this is related to #41
