### ISSUE TITLE
No pre-push hooks

### ISSUE THREAD

**Issue by cheehongw** [CATcher-org/WATcher#73]
**Describe the bug**
When running `git push`, no pre-push hooks are triggered at all.

**Expected behavior**
`ng lint` and other useful pre-push actions should run upon `git push`

**Additional context**
Me and @chunweii and @Echomo-Xinyu don't have pre-push hooks for WATcher
@Eclipse-Dominator apparently has pre-push hooks

My version:
- Node version: `v14.21.2`
- npm version: `6.14.17`
- git version: `git version 2.31.1.windows.1`

**Comment by vigneshsankariyer1234567890** [comment]
I also have pre-push hooks working for WATcher

**Comment by vigneshsankariyer1234567890** [comment]
node version: 14.15.1 (installed using nvm)
npm version: 6.14.8

**Comment by nknguyenhc** [comment]
Currently, we have got pre-push hooks to work.
