### ISSUE TITLE
Keep User Profiles hovering after scrolling down

### ISSUE THREAD

**Issue by Echomo-Xinyu** [CATcher-org/WATcher#74]
**Is your feature request related to a problem? Please describe.**
When scrolling down to read more issues, the User Profile photos are automatically hidden and can no longer be seen unless we scroll up to the top. Having the user profiles always in sight is important to know who creates which PR or issue. Below are two screenshots of full-screen application and the card views containing user profile photos are hidden.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/25452497/216889816-b9f54352-1ff1-4571-9b46-d5d7a12dc6ae.png">

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/25452497/216889850-7fddbd60-b167-43be-8d68-70d5914bee16.png">

**Describe the solution you'd like**
Having the user profile mat-card always in sight while scrolling down while hiding other less important information like filter.

**Additional context**

**Comment by chia-yh** [comment]
I think this solution would be a good improvement to the UI, however, I'd like to propose an alternative where the PR/issues are contained in scrollable containers for each author. This allows the filter bar to remain in sight, allowing users to be able to change the filter settings easily, while also being able to see the author of each PR/issue, which solves the problem raised. Having the PR/issues be in individual scrollable containers for each author would also mean that scrolling through the PR/issues of a single author won't potentially hide a PR/issue of another author that the user may be looking at.

To illustrate what I mean, I managed to tweak `card-view` component slightly to get the following result:
![image](https://github.com/CATcher-org/WATcher/assets/105497890/da2c6ffe-dc68-4d82-a182-d70ccbf0c446)
As shown above, users would be able to individually look through the PR/issues of a particular author, and there would also be no need for users to scroll up if they would like to change the filter settings. However, I'm not sure if this alternative would be an improvement over the originally proposed solution.

**Comment by damithc** [comment]
> I think this solution would be a good improvement to the UI, however, I'd like to propose an alternative where the PR/issues are contained in scrollable containers for each author. This allows the filter bar to remain in sight, allowing users to be able to change the filter settings easily, while also being able to see the author of each PR/issue, which solves the problem raised. Having the PR/issues be in individual scrollable containers for each author would also mean that scrolling through the PR/issues of a single author won't potentially hide a PR/issue of another author that the user may be looking at.
> 
> To illustrate what I mean, I managed to tweak the `card-view` component slightly to get the following result: ![image](https://user-images.githubusercontent.com/105497890/248502018-da2c6ffe-dc68-4d82-a182-d70ccbf0c446.png) As shown above, users would be able to individually look through the PR/issues of a particular author, and there would also be no need for users to scroll up if they would like to change the filter settings. However, I'm not sure if this alternative would be an improvement over the originally proposed solution.
> 
> I've opened a PR in case others would like to verify how the proposed alternative looks.

@chia-yh thanks for attempting this issue. It feels like these multiple scrollbars are adding too much noise to the UI, and also takes up valuable screen space.

**Comment by cheehongw** [comment]
@chia-yh Is it possible to hide the scrollbar but keep the scrolling with CSS?

**Comment by chia-yh** [comment]
> @chia-yh Is it possible to hide the scrollbar but keep the scrolling with CSS?

That's a great idea! I'll give it a shot and and update the PR if I manage to do so!

**Comment by chia-yh** [comment]
> @chia-yh Is it possible to hide the scrollbar but keep the scrolling with CSS?

I've updated the PR, the scrollbars are now hidden while keeping the scrolling functionality as suggested above, I've updated the PR with screenshots but I'll paste them here as well.

**Chrome**:
![image](https://github.com/CATcher-org/WATcher/assets/105497890/c22f5c8d-1ac7-41fc-8ff4-72da5b135ce5)

**Firefox**:
![image](https://github.com/CATcher-org/WATcher/assets/105497890/f7a82b2a-916d-4f1e-b2f1-2dc189db01f9)

**Comment by damithc** [comment]
@chia-yh This is better. One small concern is how would the user know if the view has been scrolled down and some cards are already hidden at the top?

**Comment by chia-yh** [comment]
> @chia-yh This is better. One small concern is how would the user know if the view has been scrolled down and some cards are already hidden at the top?

I initially considered having a scrollbar thumb to the side of the container, overlaid on the PR/issues, but that would go against the goal of reducing the noise in the UI.

Exploring other possible solutions, I think implementing scroll shadows in the container would be most suitable in addressing this concern while avoiding the addition of too much noise to the UI. I found [this implementation](https://css-scroll-shadows.vercel.app) which added scroll shadows with a few lines of CSS, which I felt would be good as a more complex implementation might be harder to maintain.

With the above implementation, and modifying the html slightly so that the scroll shadows would be visible above the `app-issue-pr-card`s, I managed to get the following:

Chrome:
![scroll_shadows_chrome](https://github.com/CATcher-org/WATcher/assets/105497890/151aa779-8053-452e-aecb-76015a596eb3)

Firefox:
![scroll_shadows_firefox](https://github.com/CATcher-org/WATcher/assets/105497890/30439bfc-e0e9-45a3-beeb-4125dbe01155)

Would this be sufficient in letting the user know if the view has been scrolled down or if some cards are hidden at the top?

**Comment by damithc** [comment]
@chia-yh scroll shadows sounds good but only if they remain after the scrolling action has finished i.e., the shadow should indicate 'scrolled', not just 'scrolling right now'.

Alternatively, if the scrolling is such that the top-most card is always shown half cut-off, it immediately tells the user that there are some more cards at the top but hidden from the view.

**Comment by chia-yh** [comment]
@damithc the way its implemented at the moment, the scroll shadows are visible as long as there are cards that are not currently visible to the user, regardless of if the user is currently scrolling through. I've pushed the changes to my branch for now, in case anyone would like to see how it currently behaves.

The alternative solution sounds good as well, but would it involve obscuring part of the top/bottom-most card as long as there are more cards hidden from view? I'm not too sure how it would work, but it does sound like a viable alternative.

**Comment by damithc** [comment]
> @damithc the way its implemented at the moment, the scroll shadows are visible as long as there are cards that are not currently visible to the user, regardless of if the user is currently scrolling through. I've pushed the changes to my branch for now, in case anyone would like to see how it currently behaves.

@chia-yh I was referring to the shadow at the top. Based on the video you provided, the top shadow only appears while the list is being scrolled. The top shadow should be visible as long as there are cards hidden above it. Similarly, the bottom one should appear as long as there are cards hidden below it.

**Comment by Eclipse-Dominator** [comment]
I think a trivial way to achieve that is to insert a dummy empty block so when the page is scrolled to the bottom no shadow will be cast on the blank space.

**Comment by chia-yh** [comment]
@damithc I might be mistaken, but I think that it currently works as you mentioned. The following screenshots are taken without the list being scrolled,

With cards hidden below only:
![image](https://github.com/CATcher-org/WATcher/assets/105497890/f92e6f78-2063-420c-bda9-31c570aa60a5)

With cards hidden both above and below:
![image](https://github.com/CATcher-org/WATcher/assets/105497890/0d587fcb-752c-4e1f-a3f9-427e8d87f125)

With cards hidden above only:
![image](https://github.com/CATcher-org/WATcher/assets/105497890/ea081412-4ccf-4af5-a3e0-bea5b81a4822)

The video I provided might have been misleading as I was scrolling all the way back up at the end, but do let me know if I misunderstood somehow.

**Comment by damithc** [comment]
> @damithc I might be mistaken, but I think that it currently works as you mentioned. The following screenshots are taken without the list being scrolled,

Yes, seems OK. 👍

**Comment by Eclipse-Dominator** [comment]
Let's close this for now since the alternative solution #148 is adapted.
