### ISSUE TITLE
Remove outdated tests

### ISSUE THREAD

**Issue by cheehongw** [CATcher-org/WATcher#85]
There are many failing unit tests in WATcher. These tests are inherited from CATcher and require updating.

Reasons for failure fall under these 2 categories:
1. unit under test has been removed when changing from WATcher to CATcher
2. unit under test has undergone changes since CATcher

It should be relatively safe to fix category 1 since we are removing tests for files that don't exist anymore.

Fixes for category 2 should be done carefully, and should try to preserve tests cases as much as possible

<details>
<summary>
<h3>To refactor test:</h3>
</summary>

- [x] Login Component
- [x] Session Model
- [x] Issue Paginator
- [x] Issue Sorter
- [x] Github Label constants
- [x] Search Filter
- [x] Issue Model
- [x] Label Service
- [x] Label Filter Bar Component
- [x] Phase Service
- [x] User Service

</details>

<details>
<summary>
<h3>To remove test:</h3>
</summary>

- [x] markdown.css (in test env stylesheet)
- [x] Conflict Model
- [x] Permissions service
- [x] Unused constants

</details>

**Comment by chunweii** [comment]
Issue is related to #72

**Comment by chunweii** [comment]
@Eclipse-Dominator Are you working on this issue? If not you can unassign yourself and let others work on this

**Comment by NereusWB922** [comment]
Hi, since the outdated tests have been refactored and the pre-push hook for npm run test is also enabled, I think we can close this issue now.
