### ISSUE TITLE
Add Issues Dashboard access by URL

### ISSUE THREAD

**Issue by vigneshsankariyer1234567890** [CATcher-org/WATcher#94]
**Is your feature request related to a problem? Please describe.**
Currently, users cannot access a specific repo's dashboard directly by URL. This means that Prof is not able to create a new URL for each team to distribute the link to each team's individual dashboard. Let's add the ability to access the relevant repository's dashboard by URL. 

**Describe the solution you'd like**
Let's try to allow WATcher to grab the relevant repository's details using URL params. E.G. `/issuesViewer/{org-repo}`. Subsequently, we have 2 cases: either the user is logged in or not. We can store the relevant details in sessionStorage and extract it from sessionStorage once log-in done.

**Comment by Eclipse-Dominator** [comment]
@Echomo-Xinyu are you still working on this?

**Comment by gycgabriel** [comment]
I've just thought of this issue as well. I think it is a good enhancement to have

**Comment by LJXSean** [comment]
@Eclipse-Dominator Hi are you still working on this?
